docs/guides/exchange_guide.md
add feedback provided by @laumair 
Closes #6
=> feat(exchange-guide)/add-feedback

docs/guides/backup_security.md
add checklist, QnA and Do's and Don'ts in collaboration with @nothingismagick
=> feat(backup-security)/add-content

docs/guides/exchange_guide.md
Fixed multiple typos,
exchanged text,
added readability.
=> Fix typos & suggest text changes in exchange_guide.md

docs/introduction/path_to_chrysalis.md, docs/introduction/what_is_chrysalis.md
Changed chapter 2 & 3. 
- Changed links to protocol-rfcs instead of iota.cafe
- Added info on client libs and node APIs
- Deleted some stuff that I found slightly redundant
- Fixed some typos/rewrote things here and there
=> Conceptual changes, fixes, links, minor rewrites

docs/introduction/path_to_chrysalis.md
=> Fix milestone rfc link

docs/guides/exchange_guide.md
=> fix(typo)/add-faucet-hint

book.toml
=> fix/mdbook-config 

docs/guides/dev_guide.md
Old example address was invalid
=> Update example address

docs/guides/token_guide.md
Revised content and added a reference link to the blog post.
=> Chrysalis Doc Review III

docs/guides/global_genesis_legacy_guide.md
Added content for how to partake on the global and genesis snapshot validation/bootstrapping for Chrysalis Phase 2.
=> Partaking Guide Added

docs/guides/token_guide.md
add content to programmatically approach to migrate tokens.
=> add_Token_Migration_for_Exchanges

.github/workflows/deploy_docs_to_gh-pages.yml, docOps/docs/guides/README.md, docOps/docs/guides/backup_security.md, docOps/docs/guides/migration-mechanism.md, docOps/docs/guides/token_guide.md, docOps/docs/introduction/what_is_chrysalis.md, docOps/docusaurus.config.js, docOps/src/pages/index.js, docs/guides/dev_guide.md, docs/guides/exchange_guide.md
=> Docusaurus updates

docs/guides/token_guide.md
=> readd updated migration example

docs/guides/dev_guide.md, docs/guides/hub_guide.md, docs/guides/token_guide.md, docs/libraries/client.md, docs/libraries/wallet.md, docs/testnet.md, docs/tutorials/one-click-private-tangle.md, package.json, yarn.lock
* Fixed Broken links
* Upgraded Docusaurus version to improve mobile navigation
- Documentation fix
Changes where tested locally based on a report from https://www.drlinkcheck.com/
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.
=> Docs - Fix Broken Links

docs/libraries/client.md
- Updated docs/libraries/client.md
=> Add java links to client libraries page

docs/guides/hub_migration.md
* Added link to IOTA Discord.
* Added link to the token migration guide.
Docs site was built locally.
=> Docs - Update Hub Migration Page 

sidebars.js
Fixed sidebar to include tutorials
- Documentation Fix
Wiki was built locally.
=> Docs - Fix sidebar

docs/guides/backup_security.md, docs/guides/exchange.md, docs/guides/hub_migration.md, docs/guides/migration_mechanism.md, docs/guides/snapshot_validation_bootstrapping.md, docs/guides/token_migration.md
Applied style guide and diataxis changes to Chrysalis documentation including the:
- exchange
- token migration
- migration mechanisms
- hib migration
- backup and secuirty
- and snapshot validation/bootstraping
guides.
=> Style Guide and Diataxis Review - Chrysalis III

docs/node_software.md
Please update ... if available.
Link target  is not working any more
- Documentation Enhancement
=> Marked outdated link to swagger API

docusaurus.config.js
Added the needed version info. 
Checklist:
https://github.com/iota-community/iota-wiki/issues/555
TODO
=> Add documentation version info for IOTA

.github/workflows/test-docs-build.yml, docs/guides/exchange.md, docs/introduction/what_is_stardust.md, docs/welcome.md, docusaurus.config.js, package.json, yarn.lock
Added the needed version info. 
Checklist:
https://github.com/iota-community/iota-wiki/issues/555
TODO
=> Add documentation version info for Develop

docusaurus.config.js
Fixed the edit url
https://github.com/iota-community/iota-wiki/issues/636
- Bug fix (a non-breaking change that fixes an issue)
- Documentation Fix
=> Fix edit url

docs/explanations/ledger/simple_transfers.md
TIP URLs are now pointing to iotaledger 
Choose a type of change, and delete any options that are not relevant.
- Enhancement (a non-breaking change that adds functionality)
Change URLs
Tick the boxes that are relevant to your changes, and delete any items that are not.
- [z ] I have followed the contribution guidelines for this project
=> Fix TIP pointers

docs/reference/networks/shimmer.md
Added the Shimmer endpoints
- Documentation Enhancement
=> Update Shimmer endpoints
